permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""

title: "M_Tech.log"
email: "jinmeng260@yahoo.com"
description: "Knowlege,tips,thought&sketches"
#beian:
github_username:  "jinmeng260"
#swiftype_searchId: "9TDAXeK2smEEtWndRZJB"
duoshuo_shortname: "adjustment"
baidu_tongji_id: "53d63f40f6eef2f51c5cf14443efe386"


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js, toc.js]



url: "https://jinmeng260.github.io"
imgrepo: "https://jinmeng260.github.io/static/img"

# url: "http://127.0.0.1:4000"
# imgrepo: "http://127.0.0.1:4000/static/img"

encoding: utf-8
